# Dependencies
markdown:         redcarpet
highlighter:	  true

# Permalinks
permalink:        pretty

# Setup
title:            days in the cloud
tagline:          wasik mursalin's tech blog
url:              http://rushafi.github.io
paginate:         1
baseurl:          /
author:
  name:           Wasik Mursalin
  url:            http://www.toptal.com/ios#mobility-in-daily-life
  email:          rushafi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Header Pages
pages_list:
  About:		  '/about'
  Posts:		  '/archive'
  Feed:			  '/atom.xml'